FROM python:3.10-slim


# --- Tabular / data analysis stack ---
RUN pip install --no-cache-dir \
    pandas matplotlib openpyxl xlrd \
    statsmodels scipy seaborn \
    streamlit plotly \
    sqlalchemy pymysql sqlparse psycopg2-binary
