FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    numpy==1.26.4 \
    pandas==2.1.4 \
    matplotlib==3.8.2 \
    openpyxl==3.1.2 \
    xlrd==2.0.1 \
    statsmodels==0.14.1 \
    scipy==1.11.4 \
    seaborn==0.13.0 \
    plotly==5.18.0 \
    sqlalchemy==2.0.23 \
    pymysql==1.1.0 \
    sqlparse==0.4.4 \
    psycopg2-binary==2.9.9 \
    scikit-learn==1.3.2 \
    xgboost==2.0.2
